# Generated by Django 3.1.1 on 2020-10-19 19:04

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Phone Numbers Only', max_length=31),
        ),
    ]
