# Generated by Django 3.1.1 on 2020-10-23 18:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20201023_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('first', 'middle', 'last')},
        ),
    ]
