# Generated by Django 3.1.1 on 2020-10-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20201023_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='middle',
            field=models.CharField(max_length=50),
        ),
    ]
