# Generated by Django 3.1.1 on 2020-10-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20201019_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='desctiprion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='desctiprion',
            new_name='description',
        ),
    ]
