# Generated by Django 3.1.1 on 2020-10-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20201019_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, default="Divide air. Fruit replenish evening firmament had own can't itself life. Living can't. Likeness brought without winged yielding us, may. Isn't you'll man fruit don't evening midst. Created air gathered. Have greater and without to living.\nWere evening day two lesser fruitful created you'll moveth, he under very air wherein sea earth. Don't our it night had creeping first night you spirit.\nLesser blessed fill a herb. Green own, created light make their face man you had of Creeping cattle multiply every Divided and. Spirit without form moveth also divided, make it land meat open they're green, face stars divided."),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, default="Divide air. Fruit replenish evening firmament had own can't itself life. Living can't. Likeness brought without winged yielding us, may. Isn't you'll man fruit don't evening midst. Created air gathered. Have greater and without to living.\nWere evening day two lesser fruitful created you'll moveth, he under very air wherein sea earth. Don't our it night had creeping first night you spirit.\nLesser blessed fill a herb. Green own, created light make their face man you had of Creeping cattle multiply every Divided and. Spirit without form moveth also divided, make it land meat open they're green, face stars divided."),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('num', 'property')},
        ),
    ]
