# Generated by Django 3.1.1 on 2020-10-19 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20201020_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
