# Generated by Django 3.1.1 on 2020-10-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20201020_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property'),
        ),
    ]
