# Generated by Django 3.1.1 on 2020-10-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20201023_1729'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('property', 'num')},
        ),
    ]
