# Generated by Django 3.1.1 on 2020-10-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lease',
        ),
    ]
