# Generated by Django 3.1.1 on 2020-10-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_lease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lease',
        ),
    ]
