# Generated by Django 3.1.1 on 2020-10-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_lease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='contact',
            new_name='leasee',
        ),
    ]
