# Generated by Django 3.1.1 on 2020-10-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0006_auto_20201025_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='leasee',
            new_name='tenant',
        ),
    ]
