# Generated by Django 3.1.1 on 2020-11-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0007_auto_20201025_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lease',
            options={'ordering': ['property', 'unit', '-start', 'end']},
        ),
    ]
