# Generated by Django 3.1.1 on 2020-12-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0008_auto_20201123_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lease',
            options={'ordering': ['-start', 'end', 'property', 'unit']},
        ),
    ]
