# Generated by Django 3.1.1 on 2020-12-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0009_auto_20201230_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
