# Generated by Django 3.1.1 on 2020-12-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20201123_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.CharField(choices=[('Rent Amount', 'Rent Amount'), ('Security Deposit', 'Security Deposit'), ('Water Fee', 'Water Fee'), ('Electricity Fee', 'Electricity Fee'), ('Service Fee', 'Service Fee')], default='Rent Amount', max_length=50),
        ),
    ]
