# Generated by Django 3.1.1 on 2020-12-01 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20201123_2315'),
        ('accounting', '0007_invoice_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='properties.unit'),
        ),
    ]
