# Generated by Django 3.1.1 on 2020-12-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20201201_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Invoice',
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.invoice'),
        ),
    ]
