# Generated by Django 3.1.1 on 2020-12-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20201123_2315'),
        ('accounting', '0012_auto_20201204_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.unit'),
        ),
    ]
